### ISSUE TITLE
Problem with Descriptive Text

### ISSUE THREAD

**Issue by owletlizzy** [UWM-Libraries/GeoDiscovery-Utils#21]
https://geodiscovery-dev.uwm.edu/catalog/SheboyganCounty-7dfa959d35ef406cac8e00819e9de3200 

&amp; present

NOTE: This data may crash the application.

**Comment by owletlizzy** [comment]
https://geodiscovery-dev.uwm.edu/catalog/SheboyganCounty-2675e65520fc4ce5ba1548fcc005fb350
&quot;source&quot

**Comment by srappel** [comment]
Note to self: The [`html`](https://docs.python.org/3/library/html.html) library in Python handles and corrects HTML entities like `&amp`, `&quot`, and other special symbols. The `html` library's [`unescape`](https://docs.python.org/3/library/html.html#html.unescape) function can convert these HTML entities back to their original characters.

**Comment by srappel** [comment]
https://github.com/UWM-Libraries/GeoDiscovery-Utils/commit/8bf3efb7abbb86febf3b18a56a3f58e569fcb249
